sudo: false

language: node_js

matrix:
  include:
    - node_js: "0.12"
    - node_js: "0.12"
      env: BROWSER=1
    - node_js: "4"
    - node_js: "5"
    - node_js: "6"
    - node_js: "6"
      env: BROWSER=1
